#!/bin/bash
USAGE="Usage: make_clean.sh BUILDOUT_DIR\n\
\n\
Remove files generated by the buildout, reverting it to its initial state.\n"

BUILDOUT_DIR=$1

if [ ! $BUILDOUT_DIR ]
then
    echo -e $USAGE
    exit 1
fi

cd $BUILDOUT_DIR
rm -rf develop-eggs *.tmp eggs var parts downloads .installed.cfg fake-eggs bin
